version: "3"
services: 
    api:
        build: .
        depends_on:
            - postgres
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app:ro
        command: uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload
        # env_file:
        #     - ./.env bu ve aşağıdaki şekilde de env var. verebiliriz
        environment:
            - DATABASE_HOSTNAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_USERNAME=postgres
            - DATABASE_PASSWORD=1234
            - DATABASE_NAME=fastapi
            - SECRET_KEY=LJoJoavluBc8vwvWP9WzEruAlOqOyTdc8oPYK282d2AdFoOfjY
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=30
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=123123
            - POSTGRES_DB=fastapi
        
        volumes:
            - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db: 